# Site settings
title: ion-book
email: ing.carlosandresrojas@gmail.com
description: "Blog sobre Ionic Framework en Español"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ion-book.com" # the base hostname & protocol for your site
twitter_username: carlosrojas_o
github_username: carlosrojaso

markdown: markdown

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
