# Site settings
title: ion-book
description: "Blog sobre Ionic Framework en Español"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ion-book.com" # the base hostname & protocol for your site
book-url: "http://j.mp/1Us5Y5B"
book-img: "http://i.imgur.com/cfKvAxi.jpg"

courses-url: "http://bootcampwithus.usefedora.com/"

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

#permalink: /:categories/:title

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
  
authors:
  nicobytes:
    name: Nicolas Molina
    website: "http://www.nicobytes.com/"
  carlosrojas:
    name: Carlos Rojas
    website: "http://www.carlosrojasblog.com/"

social_links: 
  - url: "http://goo.gl/forms/ZCEc0cr3jydgK2wv1"
    title: "Slack"
    icon: "fa-slack"