# Site settings
title: ion-book
description: "Blog sobre Ionic Framework en Español"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ion-book.com" # the base hostname & protocol for your site
book-url: "/"
book-img: "http://i.imgur.com/cfKvAxi.jpg"
cover: "http://i.imgur.com/cfKvAxi.jpg"
timezone: "America/Bogota"

courses-url: "http://bootcampwithus.usefedora.com/"

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

permalink: /:categories/:title

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
  
authors:
  nicobytes:
    name: Nicolas Molina
    url: "/nicobytes"
    avatar: "http://i.imgur.com/mwT2iig.png"
    website: "http://nicobytes.com"
    bio: "Soy desarrollador web especializado en el área de FrontEnd & HybripApps, enfocado en aprendizaje de JS y al desarrollo de apps con Angular2 y Ionic2. Mis pasiones son el desarrollo de productos, compartir con las comunidades de desarrollo y viajar por todo el mundo."
    social_links:
      - link: "https://twitter.com/nicobytes"
        icon: "fa-twitter"
      - link: "https://github.com/nicobytes"
        icon: "fa-github"
      - link: "https://co.linkedin.com/in/nicobytes"
        icon: "fa-linkedin"
      - link: "https://www.facebook.com/nicolas.molina.127"
        icon: "fa-facebook"
  carlosrojas:
    name: Carlos Rojas
    url: "/carlosrojas"
    avatar: "http://i.imgur.com/ecNB0is.png"
    website: "http://www.carlosrojasblog.com/"
    bio: "Soy un creativo, organizado, autodidacta emprendedor y líder. Disfruto de enseñar a las personas a programar."
    social_links:
      - link: "https://twitter.com/carlosrojas_o"
        icon: "fa-twitter"
  daniel_lsanchez:
    name: "Daniel Londoño Sanchez"
    url: "/daniel_lsanchez"
    avatar: "http://i.cubeupload.com/lIAZlV.png"
    bio: "Soy desarrollador de software enfocado en especializarme en desarrollo web y móvil, me gusta ayudar a las personas y dar el conocimiento que adquiero sin nada a cambio. Me apasiono por construir productos innovadores y que ayuden a la sociedad, me gustan las motos y salir a viajar en ellas."
    social_links:
      - link: "https://twitter.com/daniel_lsanchez"
        icon: "fa-twitter"
      - link: "https://www.linkedin.com/in/daniel-londo%C3%B1o-61296b84"
        icon: "fa-linkedin"
      - link: "https://www.facebook.com/daniel.l.sanchez.501"
        icon: "fa-facebook"

social_links: 
  - url: "https://twitter.com/ion_book"
    title: "Twiiter"
    icon: "fa-twitter"
  - url: "https://www.facebook.com/ionbook/"
    title: "Facebook"
    icon: "fa-facebook"
  - url: "http://goo.gl/forms/ZCEc0cr3jydgK2wv1"
    title: "Slack"
    icon: "fa-slack"
  