# Site settings
title: ion-book
description: "Blog sobre Ionic Framework en Español"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ion-book.com" # the base hostname & protocol for your site
bookurl: "http://j.mp/1Us5Y5B"

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
  
authors:
  nicobytes:
    name: Nicolas Molina
    image: 60fd5218fff6927c0ed376cce01c5460
    web: http://www.richtaur.com/
    twitter: nicobytes
    github: nicobytes
  carlosrojas:
    name: Carlos Rojas
    image: 76dbcc74021b8039f14c7b583978b56d
    web: http://nicobytes.com
    twitter: carlosrojas_o
    github: carlosrojas_o
