# Site settings
title: ion-book
description: "Blog sobre Ionic Framework en Español"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ion-book.com" # the base hostname & protocol for your site
bookurl: "http://j.mp/1Us5Y5B"

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
  
authors:
  nicobytes:
    name: Nicolas Molina
    website: "http://www.nicobytes.com/"
  carlosrojas:
    name: Carlos Rojas
    website: "http://www.carlosrojasblog.com/"

nav_links: 
  - url: "http://goo.gl/forms/ZCEc0cr3jydgK2wv1"
    title: "Slack"
  - url: "http://bootcampwithus.usefedora.com/"
    title: "Cursos"
  - url: "http://j.mp/1Us5Y5B"
    title: "Comprar"