# ==============================================================
# General
title: "ion-book, La Comunidad de Ionic Framework en español"
description: "Aprende Ionic 2 y desarrolla increibles apps para Android y IOS."
keywords: "ion-book,html5,javascript,mobile,ionic,hybrid,phonegap,cordova,native,ios,android,angularjs,ionic 2,angular 2,curso de ionic 2, aprender ionic 2,ionic framework,hacer aplicaciones con ionic,aplicaciones hibridas"
baseurl: ""
path: "https://www.ion-book.com"
url: "https://www.ion-book.com"
urlblog: 'https://www.ion-book.com/blog'
cover: "images/cover.jpg"
timezone: "America/Bogota"
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
permalink: blog/:categories/:title/
redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
sass:
    style: compressed
excerpt_separator: <!--summary-->
# ==============================================================
# Banner Course
banner_course:
  text: 'Hemos creado un increible curso de nuestra experiencia en Colombia, Chile, Bolivia y Peru.'
  btn_text: 'Ver Curso'
  url: 'http://bootcampwithus.usefedora.com/p/curso-profesional-ionic-2-0'
# ==============================================================
# Banner Slack
banner_slack:
  title: 'Únete a nuestra comunidad'
  text: 'Únete a nuestro canal de slack y podras interactuar con toda la comunidad hispana en ionic.'
  url: 'http://goo.gl/forms/ZCEc0cr3jydgK2wv1'
  btn_text: 'Unete'
# ==============================================================
# Menu Header
menu_header:
  - title: Blog
    url: '/blog'
    target: '_self'
  - title: Cursos
    url: 'http://academia.ion-book.com/'
    target: '_blank'
  
# ==============================================================
# Menu Footer
menu_footer:
  - title: Home
    url: '/'
    target: '_self'
  - title: Blog
    url: '/blog'
    target: '_self'
  - title: Autores
    url: '/blog/authors'
    target: '_self'
  - title: Libro
    url: 'https://libro.ion-book.com/'
    target: '_blank'

# ==============================================================
# Social Links
social_links: 
  - url: "https://twitter.com/ion_book"
    title: "Twiiter"
    icon: "icon-social-twitter"
  - url: "https://www.facebook.com/ionbook/"
    title: "Facebook"
    icon: "icon-social-facebook"
  - url: "http://goo.gl/forms/ZCEc0cr3jydgK2wv1"
    title: "Slack"
    icon: "icon-slack"
  - url: "https://www.youtube.com/channel/UCxs-DaSRmp8k23n79WjXndw"
    title: "Youtube"
    icon: "icon-social-youtube"
  - url: "https://www.instagram.com/ion_book"
    title: "Instagram"
    icon: "icon-social-instagram-outline"
# ==============================================================
# Home Page
home:
  banner_title: "Aprende <span class='underline'>Ionic 2</span> y desarrolla increibles apps para Android y IOS."
  banner_text: "Inscríbete en nuestra lista de correos, recibe las últimas noticias y un paso a paso para construir tu primera App en Ionic 2."
  topics_title: "¿Que aprenderás?"
  topics_text: "Construye la app que siempre soñaste usando tecnologias Web."
  topics_video: "KVoW-1tRfXM"
  topics:
    - title: 'Conecta con Firebase 3'
      icon: 'icon-fireball'
      text: 'Conecta bases de datos en tiempo real con Firebase Database y Firebase Auth.'
    - title: 'Enviar Push Notifications'
      icon: 'icon-android-notifications'
      text: 'Aprende a implementar el sistema de mensajeria Push.'
    - title: 'Implementa Ionic Native'
      icon: 'icon-ionic'
      text: 'Accese al recursos nativos del dispositivo, como Camera, Geolocation etc.'
    - title: 'Conexion a API REST'
      icon: 'icon-code-working'
      text: 'Conecta tu servicio backend usando observables .'
    - title: 'Angular 2 y Typescript '
      icon: 'icon-social-angular'
      text: 'Aprende Angular 2 y Typescript para desarrollar con Ionic 2.'
    - title: 'UI/UX usando SASS'
      icon: 'icon-social-sass'
      text: 'Modifica y crea tu propia interfaz haciendo uso de SASS.'
    - title: 'Reactive Forms & Validations'
      icon: 'icon-android-list'
      text: 'Aprende a controlar formularios y manejar poderosas validaciones.'
    - title: 'Publica tu app en tiendas'
      icon: 'icon-upload'
      text: 'Compila y publica tu increible app en Google play y App store'
    - title: 'Aprende con buenas practicas'
      icon: 'icon-android-favorite'
      text: 'Sigue las mejores practicas entendiendo la arquirectuta de Ionic 2.'
  blog_title: 'Nuestro Blog'
  blog_text: 'Somos una comunidad de Ionic en español. Aprende a crear apps con HTML, CSS, JS.'
  blog_btn_text: 'Ver más artículos'
# ==============================================================
# Authors
authors:
  - id: 'nicobytes'
    name: Nicolas Molina
    url: "/blog/authors/nicobytes"
    avatar: "http://i.imgur.com/mwT2iig.png"
    website: "http://nicobytes.com"
    bio: "Soy desarrollador web especializado en el área de FrontEnd & HybripApps, enfocado en aprendizaje de JS y al desarrollo de apps con Angular2 y Ionic2. Mis pasiones son el desarrollo de productos, compartir con las comunidades de desarrollo y viajar por todo el mundo."
    social_links:
      - link: "https://twitter.com/nicobytes"
        icon: "icon-social-twitter"
      - link: "https://github.com/nicobytes"
        icon: "icon-social-octocat"
      - link: "https://co.linkedin.com/in/nicobytes"
        icon: "icon-linkedin"
      - link: "https://www.facebook.com/nicolas.molina.127"
        icon: "icon-social-facebook"
  - id: 'carlosrojas'
    name: Carlos Rojas
    url: "/blog/authors/carlosrojas"
    avatar: "http://i.imgur.com/ecNB0is.png"
    website: "http://www.carlosrojasblog.com/"
    bio: "Carlos Rojas es Google Product Strategy Expert. Cuando no esta dando charlas en conferencias sobre Angular, Ionic o TypeScript da cursos en Startupers Academy."
    social_links:
      - link: "https://twitter.com/carlosrojas_o"
        icon: "icon-social-twitter"
      - link: "https://youtube.com/carlosrojas84"
        icon: "icon-social-youtube"
  - id: "daniel_lsanchez"
    name: "Daniel Londoño Sanchez"
    url: "/blog/authors/daniel_lsanchez"
    avatar: "http://i.cubeupload.com/lIAZlV.png"
    bio: "Soy desarrollador de software enfocado en especializarme en desarrollo web y móvil, me gusta ayudar a las personas y dar el conocimiento que adquiero sin nada a cambio. Me apasiono por construir productos innovadores y que ayuden a la sociedad, me gustan las motos y salir a viajar en ellas."
    social_links:
      - link: "https://twitter.com/daniel_lsanchez"
        icon: "icon-social-twitter"
      - link: "https://www.linkedin.com/in/daniel-londo%C3%B1o-61296b84"
        icon: "icon-linkedin"
      - link: "https://www.facebook.com/daniel.l.sanchez.501"
        icon: "icon-social-octocat"
  - id: "levanocarlos"
    name: "Levano Carlos"
    url: "/blog/authors/levanocarlos"
    website: "http://calevano.github.io/"
    avatar: "https://firebasestorage.googleapis.com/v0/b/ion-book.appspot.com/o/authors%2Flevanocarlos.jpg?alt=media"
    bio: "Desarrollador Web, Ingeniero de Sistemas, amante de Laravel , IonicFramework, ReactNative, PHP, manoseando Android y Swift. Amante del café y series de Netflix."
    social_links:
      - link: "https://twitter.com/calevano"
        icon: "icon-social-twitter"
      - link: "https://www.linkedin.com/in/calevano/"
        icon: "icon-linkedin"
      - link: "https://github.com/calevano"
        icon: "icon-social-octocat"
  - id: "mayrititis"
    name: "Mayra Rodríguez"
    url: "/blog/authors/mayrititis"
    avatar: "https://a248.e.akamai.net/secure.meetupstatic.com/photos/event/4/f/f/8/600_454640472.jpeg"
    website: "http://mayrarodriguez.me/"
    bio: "Soy Ingeniera en Computación egresada de la Universidad Fermín Toro, Cabudare Edo. Lara. Me dedico al Desarrollo Web Full Stack y Móvil de manera Freelance. Me siento aficionada por el UX y el UI, así como también el desarrollo de aplicaciones innovadoras."
    social_links:
      - link: "https://twitter.com/mayrititis"
        icon: "icon-social-twitter"
      - link: "https://www.linkedin.com/in/mayrarodriguez1709"
        icon: "icon-linkedin"
      - link: "https://www.facebook.com/mayrititis"
        icon: "icon-social-octocat"
  - id: "unjavascripter"
    name: "Diego Coy"
    url: "/blog/authors/unjavascripter"
    avatar: "http://i.cubeupload.com/fiMbBz.png"
    bio: "I spend my time learning about new technologies and coding. I really enjoy developing web applications using JavaScript. I'm currently working with (and loving) AngularJS. I founded a group where people can learn and share about AngularJS in Colombia, there I'm the organizer and sometimes speaker. I've been enjoying teaching people about new cool technologies "
    social_links:
      - link: "https://twitter.com/unjavascripter"
        icon: "icon-social-twitter"
      - link: "https://github.com/unjavascripter"
        icon: "icon-social-octocat"
  - id: "javebratt"
    name: "Jorge Vergara"
    url: "/blog/authors/javebratt"
    avatar: "https://s9.postimg.org/fhmw4iggf/Iu_N5_UI0o.jpg"
    bio: "Ayudo a emprendedores que están atacando proyectos de impacto social a planear y construir la primera versión de su aplicación móvil para que puedan salir al mercado rápido. Ayudo a desarrolladores de Ionic2 a usar esos conocimientos para construir aplicaciones basadas en Firebase."
    social_links:
      - link: "https://twitter.com/javebratt"
        icon: "icon-social-twitter"
      - link: "https://facebook.com/javebrattDev"
        icon: "icon-social-octocat"
  - id: "jorgecano"
    name: "Jorge Cano"
    url: "/blog/authors/jorgecano"
    avatar: "https://firebasestorage.googleapis.com/v0/b/ion-book.appspot.com/o/authors%2Fangulargderedondo.png?alt=media&token=71a0f757-4f37-4958-8350-f54201f5fe78"
    bio: "Después de más de 9 años desarrollando, Jorge es un full stack developer avocado a las tecnologías en javascript. Hoy en día Jorge es Director de “departamento de nuevas tecnologías” en el cual prueba y decide qué tecnologías utilizar para brindar el mejor servicio performance y seguridad con Angular / Firebase y otras tecnologías de punta… Profesor de varios cursos relacionados a javascript, Google Developer Expert en tecnologías web y Angular Developer Expert , speaker internacional, y escritor de artículos técnicos.
    "
    social_links:
      - link: "https://twitter.com/jorgeucano"
        icon: "icon-social-twitter"
      - link: "https://github.com/jorgeucano"
        icon: "icon-social-octocat"
  - id: "thecouk"
    name: "Oscar Andrade"
    url: "/blog/authors/thecouk"
    avatar: "https://firebasestorage.googleapis.com/v0/b/ion-book.appspot.com/o/authors%2FImage%20uploaded%20from%20iOS%20(1).jpg?alt=media&token=f6c0d80a-893e-4b70-90f3-7843fbe3d54f"
    bio: "Web & Mobile Developer, PHP, Laravel, AJAX, Ionic, Angular, Javascript - Creo que el conocimiento es una de las pocas cosas que no se pierde cuando se comparte.
    "
    social_links:
      - link: "https://twitter.com/thecouk"
        icon: "icon-social-twitter"
      - link: "https://github.com/thecouk"
        icon: "icon-social-octocat"
# ==============================================================
# Publications
publications:
  - url: "http://www.paywithapost.de/pay?id=b1b5bde8-da59-4bc4-b6f9-1b62231c2884"
    title: "Empieza con este paso a paso de como hacer una App de Fotos con Ionic 1."
    cover: "https://firebasestorage.googleapis.com/v0/b/ion-book.appspot.com/o/ebooks%2Fion-gram.jpg?alt=media&"
    summary: "Todos soñamos con hacer el proximo Instagram. Empieza con este paso a paso de como hacer una App de Fotos con Ionic 1."
  - url: "http://www.paywithapost.de/pay?id=356c87df-fcf3-4b7c-baa8-dec66570445d"
    title: "Construye un App de Tareas"
    cover: "https://firebasestorage.googleapis.com/v0/b/ion-book.appspot.com/o/ebooks%2Fion-list.jpg?alt=media"
    summary: "Aprende a manejar Tabs en Ionic 1 realizando una App que te ayudara a aumentar tu Productividad."
  - url: "http://www.paywithapost.de/pay?id=29729e3f-6765-4e1f-8ee1-84bba161feec"
    title: "Construye un App para eventos"
    cover: "https://firebasestorage.googleapis.com/v0/b/ion-book.appspot.com/o/ebooks%2Fion-events.jpg?alt=media"
    summary: "Aprende a manejar APIs con este paso a paso de un App para eventos en Ionic 1."
# ==============================================================
# Meetups
meetups:
  - url: "https://www.meetup.com/es-ES/Hybrid-Apps-Colombia/"
    title: "Cross Apps Colombia."
    cover: "https://firebasestorage.googleapis.com/v0/b/ion-book.appspot.com/o/meetups%2Fglobal_458349563.jpeg?alt=media&token=7de43573-035f-4d6b-bd13-90b5c2b1c075"
    country: "Bogota,Colombia"
  - url: "https://www.meetup.com/es-ES/Hybrid-Apps-Chile/"
    title: "Cross Apps Chile."
    cover: "https://firebasestorage.googleapis.com/v0/b/ion-book.appspot.com/o/meetups%2Fglobal_458349563.jpeg?alt=media&token=7de43573-035f-4d6b-bd13-90b5c2b1c075"
    country: "Santiago,Chile"
  - url: "https://www.meetup.com/es-ES/Cross-Apps-Mexico/"
    title: "Cross Apps Mexico."
    cover: "https://firebasestorage.googleapis.com/v0/b/ion-book.appspot.com/o/meetups%2Fglobal_458349563.jpeg?alt=media&token=7de43573-035f-4d6b-bd13-90b5c2b1c075"
    country: "Ciudad de México, México"
  - url: "https://www.meetup.com/es-ES/Cross-Apps-Argentina/"
    title: "Cross Apps Argentina."
    cover: "https://firebasestorage.googleapis.com/v0/b/ion-book.appspot.com/o/meetups%2Fglobal_458349563.jpeg?alt=media&token=7de43573-035f-4d6b-bd13-90b5c2b1c075"
    country: "Buenos Aires, Argentina"
  - url: "https://www.meetup.com/es-ES/Meetup-de-JavaScript-en-San-Jose/"
    title: "Cross Apps Costa Rica."
    cover: "https://firebasestorage.googleapis.com/v0/b/ion-book.appspot.com/o/meetups%2Fglobal_458349563.jpeg?alt=media&token=7de43573-035f-4d6b-bd13-90b5c2b1c075"
    country: "San Jose, Costa Rica"
# ==============================================================
# Blog
blog:
  count_related_posts: 3
# ==============================================================
# Footer
footer:
  text: 'Somos un pequeño pedazo del Internet empoderado por la Comunidad de Ionic en Español. 
  
  Aprende a crear apps con HTML, CSS y Javascript con nuestros Tutoriales, Libro, Slack y Publicaciones.'
# ==============================================================
# Subscribe
subscribe:
  btn_text: 'Subscríbete'
  success_text: 'Gracias! Ahora estas suscrito a ion-book.'

